[build]
  command = "node build.js"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "https://karmazin.netlify.app/*"
  to = "https://karmazin.space/:splat"
  status = 301
  force = true
